workers:
    docker_compose: ~
    tailwind_app:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch', 'assets/styles/app.css', '-vvv']
    tailwind_toolkit_shadcn:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch', 'assets/styles/toolkit-shadcn.css', '-vvv']
    tailwind_live_memory:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch', 'assets/styles/demos/live-memory.css', '-vvv']

http:
    port: 9044
    use_gzip: true
