workers:
    docker_compose: ~
    tailwind_app:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch', 'assets/styles/app.css', '-vvv']
    tailwind_toolkit:
        cmd: ['sh', '-c', 'trap "kill 0" EXIT; for input in var/ux_toolkit/preview/ux-toolkit-*.css; do symfony console tailwind:build --watch "$input" -vvv & done; wait']
    tailwind_live_memory:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch', 'assets/styles/demos/live-memory.css', '-vvv']
    tailwind_inspector:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch', 'assets/styles/demos/inspector.css', '-vvv']

http:
    port: 9044
    use_gzip: true
