<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\EventListener;

use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\KernelEvents;

/**
 * Serves Markdown versions of pages for LLM tools and agents.
 *
 * Two access methods are supported:
 *  1. Content negotiation: "Accept: text/markdown" header on any page URL
 *  2. URL suffix: appending ".md" to any page URL (e.g. /turbo.md)
 *
 * The corresponding .md files must be pre-generated by the
 * app:generate-llms-files command into var/llms/.
 */
#[AsEventListener(event: KernelEvents::REQUEST, priority: 200)]
class MarkdownContentNegotiationListener
{
    public function __construct(
        #[Autowire('%app.llms_dir%')] private readonly string $llmsDir,
    ) {
    }

    public function __invoke(RequestEvent $event): void
    {
        if (!$event->isMainRequest()) {
            return;
        }

        $request = $event->getRequest();

        if (!\in_array($request->getMethod(), ['GET', 'HEAD'], true)) {
            return;
        }

        $path = $request->getPathInfo();

        // Method 1: URL ends with .md suffix
        if (str_ends_with($path, '.md')) {
            $mdFile = $this->resolveMdFile($path);
            if (null !== $mdFile && null !== ($response = $this->createResponse($mdFile))) {
                $event->setResponse($response);
            }

            return;
        }

        // Method 2: Content negotiation via Accept header
        $acceptableTypes = $request->getAcceptableContentTypes();
        if (!\in_array('text/markdown', $acceptableTypes, true)) {
            return;
        }

        // text/markdown must be preferred over text/html
        $markdownPriority = array_search('text/markdown', $acceptableTypes, true);
        $htmlPriority = array_search('text/html', $acceptableTypes, true);
        if (false !== $htmlPriority && $htmlPriority < $markdownPriority) {
            return;
        }

        // Map the URL to the corresponding .md file
        if ('/' === $path) {
            $mdPath = '/index.html.md';
        } else {
            $mdPath = rtrim($path, '/').'.md';
        }

        $mdFile = $this->resolveMdFile($mdPath);
        if (null === $mdFile) {
            return;
        }

        $response = $this->createResponse($mdFile);
        if (null === $response) {
            return;
        }

        $event->setResponse($response);
    }

    /**
     * Resolves a .md URL path to the corresponding file in var/llms/.
     *
     * For a URL like "/turbo.md", the file is at "var/llms/turbo.md".
     * For "/index.html.md", the file is at "var/llms/index.html.md".
     */
    private function resolveMdFile(string $path): ?string
    {
        $mdFile = $this->llmsDir.$path;

        if (!is_file($mdFile)) {
            return null;
        }

        // Prevent path traversal outside var/llms/
        $realPath = realpath($mdFile);
        $realLlmsDir = realpath($this->llmsDir);
        if (false === $realPath || false === $realLlmsDir || !str_starts_with($realPath, $realLlmsDir.\DIRECTORY_SEPARATOR)) {
            return null;
        }

        return $realPath;
    }

    private function createResponse(string $mdFile): ?Response
    {
        $content = file_get_contents($mdFile);
        if (false === $content) {
            return null;
        }

        return new Response($content, 200, [
            'Content-Type' => 'text/markdown; charset=UTF-8',
            'X-Content-Type-Options' => 'nosniff',
        ]);
    }
}
