name: Tests

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.5'

            -   name: Install dependencies
                uses: ramsey/composer-install@v3

            -   name: Build Sass assets
                run: php bin/console sass:build

            -   name: Smoke Tests
                run: vendor/bin/phpunit --testsuite "Smoke Tests"

            -   name: Tests
                run: vendor/bin/phpunit
